### ISSUE TITLE
bug: Config breaks for hyprland v0.45.2

### ISSUE THREAD

**Issue by cryogon** [HyDE-Project/Hyde-cli#100]
### Did you check docs and existing issues?

- [X] I have read all the Hyde docs
- [X] I have searched the existing issues of Hyde
- [X] I have searched the existing issues of plugins related to this issue

### Hyde version

v0.6.0-24-ge5d5a6a

### Operating system/version

6.12.1-arch1-1

### Describe the bug

After the hyprland v0.45.x update, the config is breaking since some namespaces are moved. 

### Steps To Reproduce

update the hyprland to newer version

### Expected Behavior

the configs shouldn't break

**Comment by kRHYME7** [comment]
update the themes

**Comment by cryogon** [comment]
I see. thanks 🙏
