### ISSUE TITLE
feature: add text extraction tool feature

### ISSUE THREAD

**Issue by mahaveergurjar** [HyDE-Project/Hyde-cli#92]
### Did you check the docs?

- [X] I have read all the Hyde docs

### Is your feature request related to a problem? Please describe.

Text copy from image 

### Describe the solution you'd like

I make a script extract text from image using slurp and tesseract tool 

### Describe alternatives you've considered

or make any other script for this 

### Additional context

https://github.com/user-attachments/assets/8d90ad7d-d86d-4ed0-bd50-208a8f2cd517

**Comment by kRHYME7** [comment]
``` Hyde run screencap --scan ```

**Comment by mahaveergurjar** [comment]
Ok

**Comment by mahaveergurjar** [comment]
![image](https://github.com/user-attachments/assets/7b58ed30-fa66-4146-9078-d1942f365a71)

**Comment by kRHYME7** [comment]
That's only a warning, and should be fixed here. a809d6633aec77e735360880ee39f128e81ebc0a

**Comment by kRHYME7** [comment]
If you want to improve this script feel free to do a PR.

Here's the part of it

**Comment by mahaveergurjar** [comment]
Ok but i think its improved already

**Comment by mahaveergurjar** [comment]
can you tell me where is used this script ??
![image](https://github.com/user-attachments/assets/752b6c81-c5da-4cca-9528-e69416f8a485)

**Comment by kRHYME7** [comment]
I'm trying to make our own abstraction of grimblast as grimblast on AUR breaks sometimes
