### ISSUE TITLE
bug: HyDE theme next stops at last theme.

### ISSUE THREAD

**Issue by YuvanMichaelVivenzi** [HyDE-Project/Hyde-cli#93]
### Did you check docs and existing issues?

- [X] I have read all the Hyde docs
- [X] I have searched the existing issues of Hyde
- [X] I have searched the existing issues of plugins related to this issue

### Hyde version

Latest as of 02:12 PM IST v0.6.0-4-ga809d66

### Operating system/version

Arch

### Describe the bug

stops at Ice Age (last theme) and starts back up with MacOS (first theme) but doesn't change anything unless rofi is used

### Steps To Reproduce

Run Hyde theme next till Ice Age theme and try again. 

### Expected Behavior

Change themes like normal.

**Comment by kRHYME7** [comment]
This command only  calls `themeswitch.sh n` 
so can you run it and catch any errors.

**Comment by YuvanMichaelVivenzi** [comment]
The issue is that I use "Hyde theme next" to get a new theme at every startup. But when I reach the end of the theme list, It switches to the starting one that's MacOS and wallpaper doesn't change only waybar and cursor seem to change.

**Comment by YuvanMichaelVivenzi** [comment]
An issue with my dotfiles? https://github.com/YuvanMichael/HyDE-dotfiles

**Comment by YuvanMichaelVivenzi** [comment]
./themeswitch.sh -n works fine as well as Hyde theme next in a terminal. Maybe an Hyprland thing? idk, maybe my fault. themechange.sh manages theming.

**Comment by YuvanMichaelVivenzi** [comment]
The issue fixed itself lol

**Comment by kRHYME7** [comment]
Uhm, are you spamming it? the wallpaper script will exist if an existing process is running

**Comment by YuvanMichaelVivenzi** [comment]
> Uhm, are you spamming it? the wallpaper script will exist if an existing process is running

I don't understand

**Comment by YuvanMichaelVivenzi** [comment]
It took like 2 reboots or so, but for some reason, once I ran them from the terminal "myself manually" it somehow worked even later on without my intervention.

**Comment by kRHYME7** [comment]
Sorry very sleepy. I meant the wallpaper script will exit when another instance of it is already running. Which means spamming/pressing the keybind multiple times might cause this error.

**Comment by YuvanMichaelVivenzi** [comment]
Oh, right, since I have a new theme on every startup and with keybinds as well that might explain the issue. Thanks!
