### ISSUE TITLE
feature: update hyde-cli-git to the newer version

### ISSUE THREAD

**Issue by su1cidalma9iac** [HyDE-Project/Hyde-cli#95]
### Did you check the docs?

- [X] I have read all the Hyde docs

### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

The [AUR package](https://aur.archlinux.org/packages/hyde-cli-git) is not up to date with the source repo. It would be nice if you updated it too.

### Describe alternatives you've considered

.

**Comment by kRHYME7** [comment]
It is a git package, so it should update according to how the PKGBUILD is made. 

By default, `paru ` will install git aur packages. but for ` yay  ` there's a flag you need to add or enable. Check the yay github page.
