### ISSUE TITLE
bug: Hyde theme patch unable to install a new theme

### ISSUE THREAD

**Issue by exilonium** [HyDE-Project/Hyde-cli#99]
### Did you check docs and existing issues?

- [X] I have read all the Hyde docs
- [X] I have searched the existing issues of Hyde
- [X] I have searched the existing issues of plugins related to this issue

### Hyde version

latest - 0.6.0

### Operating system/version

Arch - Kernel - Linux 6.12.1-arch1-1

### Describe the bug

[OK] wallpapers :: [count] 54 (.gif+.jpg+.jpeg+.png)
[OK] hypr.theme :: [gtk] $GTK_THEME
[OK] ../*.tar.* :: [gtk] 
[ERROR] gtk-theme set in hypr.theme does not exist in Gtk_*.tar.*
[OK] hypr.theme :: [icon] $ICON_THEME
[OK] ../*.tar.* :: [icon] 
[ERROR] icon-theme set in hypr.theme does not exist in Icon_*.tar.*
[!!] hypr.theme :: [cursor] Not Found
[!!] hypr.theme :: [sddm] Not Found
[!!] hypr.theme :: [font] Not Found
[!!] hypr.theme :: [document-font] Not Found
[!!] hypr.theme :: [monospace-font] Not Found

### Steps To Reproduce

install a theme
ex:- External Arctic

press enter it won't install

### Expected Behavior

it should work fine

**Comment by kRHYME7** [comment]
update it

**Comment by exilonium** [comment]
what...cli?
how to do so?

**Comment by kRHYME7** [comment]
yay -S hyde-cli-git

**Comment by exilonium** [comment]
thanks i was a bit fool
it worked
